version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - n_webapp
    depends_on:
      - webapp

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - NODE_ENV=production
    env_file:
      - ./app/.env
    volumes:
      - ./app:/usr/src/webapp
      - /usr/src/webapp/node_modules
    networks:
      - n_webapp

networks:
  n_webapp:
